enter_username						: Vpiši uporabniško ime!
enter_password						: Vpiši geslo!
db_error							: Napaka na podatkovni bazi!
user_not_exists						: Uporabnik ne obstaja!
wrong_password						: Napačno geslo!
login_succeeded_hellow				: Prijava uspela! Pozdravljen
bye_bye								: Bye bye!

session_dafaq						: Session?!
cache_has_been_successfully_set		: Cache je bil uspešno nastavljen!
cache_has_been_successfully_read	: Cache je bil uspešno prebran!
cache_not_set						: Cache ni nastavljen!